FROM openjdk:17-jdk-alpine
WORKDIR /appv1

COPY target/ReservationService-0.0.1-SNAPSHOT.jar /appv1/ReservationService-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "/appv1/ReservationService-0.0.1-SNAPSHOT.jar"]