FROM openjdk:17-jdk-alpine
WORKDIR /appv1/AuthService

#COPY /appv1/AuthService/target/AuthService-0.0.1-SNAPSHOT.jar /appv1/AuthService-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "/appv1/AuthService/target/AuthService-0.0.1-SNAPSHOT.jar"]
