#FROM openjdk:17-jdk-alpine
#WORKDIR /appv1
#COPY target/FrontendService-0.0.1-SNAPSHOT.jar /appv1/FrontendService-0.0.1-SNAPSHOT.jar
#CMD ["java", "-jar", "/appv1/FrontendService-0.0.1-SNAPSHOT.jar"]