spring:

  datasource:
    url: jdbc:mariadb://mariadb:3306/auth_service
#    url: jdbc:mariadb://localhost:3306/auth_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: authservice
server:
  port: 8083
 # config:
  #  import: optional:configserver:http://configserver:8888

  #cloud:
   # config:
    #  uri: http://configserver:8888
     # enabled: true
      #profile: native
      #fail-fast: true
    #datasource:
    # url: jdbc:mariadb://mariadb:3306/auth_service
    #username: root
    #password: password
    #jpa:
    # hibernate:
    #  ddl-auto: update
    #show-sql: true
  #server:
  # port: 8083