spring:
  config:
    import: optional:configserver:http://configserver:8888
  application:
    name: authservice
  #datasource:
   # url: jdbc:mariadb://mariadb:3306/auth_service
    #username: root
    #password: password
  #jpa:
   # hibernate:
    #  ddl-auto: update
    #show-sql: true
#server:
 # port: 8083